In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Part - 2 Learn NumPy

In [2]:
import numpy as np

In [3]:
# Few Important Functions

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [4]:
a.shape

(4,)

In [5]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
b.shape

(2, 4)

In [7]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [8]:
np.dot(b, b.T)

array([[ 30,  70],
       [ 70, 174]])

In [9]:
np.random.randint(60, 100, 10)

array([82, 65, 93, 73, 74, 99, 91, 93, 98, 81])

In [10]:
matrix = np.random.randint(60, 100, (5, 5))

In [11]:
print(matrix)
print(np.max(matrix))
print(np.min(matrix))

[[85 60 66 68 73]
 [80 96 92 64 95]
 [79 66 86 86 78]
 [60 63 60 61 94]
 [81 96 82 82 87]]
96
60


In [12]:
a = np.array([0, 1, 10, 10, 2, -8, 6, 6, 6, 6,8, 10])

In [13]:
np.argmin(a) # returns indedx of the min element

5

In [14]:
b = np.unique(a)

In [15]:
b

array([-8,  0,  1,  2,  6,  8, 10])

In [17]:
b = np.unique(a, return_counts = True)

In [18]:
b

(array([-8,  0,  1,  2,  6,  8, 10]),
 array([1, 1, 1, 1, 4, 1, 3], dtype=int64))

In [19]:
b[0]

array([-8,  0,  1,  2,  6,  8, 10])

In [20]:
b[1]

array([1, 1, 1, 1, 4, 1, 3], dtype=int64)

In [21]:
b[2] # it's a tuple and this will show index out of range error

IndexError: tuple index out of range

In [22]:
# Pregram to find out the number with the highest frequency of the array

In [23]:
b

(array([-8,  0,  1,  2,  6,  8, 10]),
 array([1, 1, 1, 1, 4, 1, 3], dtype=int64))

In [24]:
index = np.argmax(b[1])

In [25]:
element = b[0][index]
print(element)

6


In [26]:
# Slicing of array
matrix

array([[85, 60, 66, 68, 73],
       [80, 96, 92, 64, 95],
       [79, 66, 86, 86, 78],
       [60, 63, 60, 61, 94],
       [81, 96, 82, 82, 87]])

In [27]:
matrix[2:4, 1:4] # slicing (1D, 2D, 3D ....)

array([[66, 86, 86],
       [63, 60, 61]])