### Numpy array vs Python lists

In [2]:
# Speed
# List

a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []

import time

start_time = time.time()

for i in range(len(a)):
    c.append(a[i] + b[i])

end_time = time.time()
print("Total Time Required ", end_time - start_time, " seconds")

Total Time Required  1.848663568496704  seconds


In [3]:
import numpy as np

In [4]:
# Numpy
a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start_time = time.time()

c = a + b

end_time = time.time()
print("Total Time Required ", end_time - start_time, " seconds")

Total Time Required  0.11302614212036133  seconds


In [5]:
# Numpy is approx 16 times faster than python lists
# This number will change according to other given conditions
1.84/0.11

16.727272727272727

In [6]:
# Memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [10]:
# Memory can be managed in numpy
a = np.arange(10000000, dtype=np.int32)
sys.getsizeof(a)

40000104

### Advanced Indexing

In [19]:
# Normal Indexing and slicing

a = np.arange(24).reshape(6, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
a[1, 2]

6

In [21]:
# a[ Row : Col ]
a[1:3, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [24]:
# Fancy Indexing 

# a[::2]
a[:, [0, 2, 3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [28]:
# Boolean Indexing
import numpy as np
a = np.random.randint(1, 100, 24).reshape(6, 4)
a

array([[65, 94, 39, 32],
       [92, 21, 69, 65],
       [39, 53,  5, 37],
       [53,  7,  2, 16],
       [29, 67, 23, 68],
       [59, 75, 14, 15]])

In [31]:
# find all numbers greater than 50
# a > 50
b = a[a > 50]

In [32]:
b

array([65, 94, 92, 69, 65, 53, 53, 67, 68, 59, 75])

In [34]:
# find out even numbers
c = a[a % 2 == 0]

In [35]:
c

array([94, 32, 92,  2, 16, 68, 14])

In [37]:
# find all numbers greater than 50 and are even
d = a[(a > 50) & (a % 2 == 0)]

In [38]:
d

array([94, 92, 68])

In [39]:
# find all numbers not divisible by 7
a[a % 7 == 0]

array([21,  7, 14])