### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [3]:
# np.array
import numpy as np

In [4]:
a = np.array([1, 2, 3])
print(a)
# This is a 1D array (a.k.a vector)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# 2D and 3D
b = np.array([[1, 2, 3], [4, 5, 6]])
# it's a 2D array (a.k.a matrix)
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# it's a 3D array (a.k.a tensor)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
#dtype
# differnt data types
print(np.array([1, 2, 3], dtype = float))
print(np.array([1, 2, 3], dtype = bool))
print(np.array([1, 2, 3], dtype = complex))

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [8]:
# np.arange -> same as range function in python
# used to create a new array
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [9]:
# with reshape
# be carefull with the numbers
np.arange(1, 13).reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [10]:
# np.ones and np.zeroes
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# np.random
np.random.random((3, 4))

array([[0.93160058, 0.39506352, 0.89673295, 0.81166846],
       [0.30899076, 0.80839408, 0.06818142, 0.95204858],
       [0.435953  , 0.34833571, 0.56986332, 0.31612712]])

In [13]:
# np.linspace
# will create a equidistance list of numbers
np.linspace(-10, 10, 10, dtype = int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [14]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [15]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [16]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [17]:
# ndim - determines the dimention of the array
a3.ndim

3

In [19]:
# itemsize
a2.itemsize

8

In [23]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [24]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Array Operations

In [25]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [28]:
# scalar operations
# arithmetic - all arithmetic operators can be used on a matrix

a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [29]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
# vector operations
# arithmetic

a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])