### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

In [4]:
a = np.array([1, 2, 3])
print(a)
# This is a 1D array (a.k.a vector)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# 2D and 3D
b = np.array([[1, 2, 3], [4, 5, 6]])
# it's a 2D array (a.k.a matrix)
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# it's a 3D array (a.k.a tensor)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
