### np.sort

Return a sorted copy of an array.
It returns a copy of the original array, so no changes will happen to the original array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np

a = np.random.randint(1, 100, 15)
a

array([26, 23, 71, 51, 42, 82, 33, 94,  9, 79, 79, 12, 29, 94, 63])

In [2]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[90, 52,  6, 29],
       [54, 98, 55, 17],
       [70, 43, 62, 29],
       [43, 10, 44, 91],
       [12, 10,  3, 15],
       [83, 53, 18, 76]])

In [3]:
np.sort(a)

array([ 9, 12, 23, 26, 29, 33, 42, 51, 63, 71, 79, 79, 82, 94, 94])

In [4]:
# decending wise sorting
np.sort(a)[::-1]

array([94, 94, 82, 79, 79, 71, 63, 51, 42, 33, 29, 26, 23, 12,  9])

In [5]:
a

array([26, 23, 71, 51, 42, 82, 33, 94,  9, 79, 79, 12, 29, 94, 63])

In [6]:
np.sort(b)

array([[ 6, 29, 52, 90],
       [17, 54, 55, 98],
       [29, 43, 62, 70],
       [10, 43, 44, 91],
       [ 3, 10, 12, 15],
       [18, 53, 76, 83]])

In [7]:
# axis = 0 -> column
# axis = 1 -> row
np.sort(b, axis = 0)

array([[12, 10,  3, 15],
       [43, 10,  6, 17],
       [54, 43, 18, 29],
       [70, 52, 44, 29],
       [83, 53, 55, 76],
       [90, 98, 62, 91]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
# code
# a
np.append(a, 200)

array([ 26,  23,  71,  51,  42,  82,  33,  94,   9,  79,  79,  12,  29,
        94,  63, 200])

In [9]:
# b
np.append(b, np.ones((b.shape[0], 1)), axis = 1)

array([[90., 52.,  6., 29.,  1.],
       [54., 98., 55., 17.,  1.],
       [70., 43., 62., 29.,  1.],
       [43., 10., 44., 91.,  1.],
       [12., 10.,  3., 15.,  1.],
       [83., 53., 18., 76.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [10]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
# axis = 0 -> column
# axis = 1 -> row
np.concatenate((c, d), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c, d), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [13]:
# code
e = np.array([1, 1, 2, 3, 2, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [15]:
a

array([26, 23, 71, 51, 42, 82, 33, 94,  9, 79, 79, 12, 29, 94, 63])

In [16]:
np.expand_dims(a, axis = 0).shape

(1, 15)

In [17]:
np.expand_dims(a, axis = 1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [18]:
a

array([26, 23, 71, 51, 42, 82, 33, 94,  9, 79, 79, 12, 29, 94, 63])

In [19]:
# find all indices with value greater than 50
np.where(a > 50)

(array([ 2,  3,  5,  7,  9, 10, 13, 14], dtype=int64),)

In [20]:
# replace all values > 50 with 0
# np.where(condition, true, false)
np.where(a > 50, 0, a)

array([26, 23,  0,  0, 42,  0, 33,  0,  9,  0,  0, 12, 29,  0,  0])

In [21]:
# replace all even numbers with 0
np.where(a%2 == 0, 0, a)

array([ 0, 23, 71, 51,  0,  0, 33,  0,  9, 79, 79,  0, 29,  0, 63])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [22]:
a

array([26, 23, 71, 51, 42, 82, 33, 94,  9, 79, 79, 12, 29, 94, 63])

In [23]:
np.argmax(a)

7

In [24]:
b

array([[90, 52,  6, 29],
       [54, 98, 55, 17],
       [70, 43, 62, 29],
       [43, 10, 44, 91],
       [12, 10,  3, 15],
       [83, 53, 18, 76]])

In [25]:
# axis = 0 -> column
# axis = 1 -> row
np.argmax(b, axis = 0)

array([0, 1, 2, 3], dtype=int64)

In [26]:
np.argmax(b, axis = 1)

array([0, 1, 0, 3, 3, 0], dtype=int64)

Extra: np.argmin

In [27]:
a

array([26, 23, 71, 51, 42, 82, 33, 94,  9, 79, 79, 12, 29, 94, 63])

In [28]:
np.argmin(a)

8

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [29]:
a

array([26, 23, 71, 51, 42, 82, 33, 94,  9, 79, 79, 12, 29, 94, 63])

In [30]:
np.cumsum(a)

array([ 26,  49, 120, 171, 213, 295, 328, 422, 431, 510, 589, 601, 630,
       724, 787], dtype=int32)

In [31]:
b

array([[90, 52,  6, 29],
       [54, 98, 55, 17],
       [70, 43, 62, 29],
       [43, 10, 44, 91],
       [12, 10,  3, 15],
       [83, 53, 18, 76]])

In [33]:
np.cumsum(b)

array([  90,  142,  148,  177,  231,  329,  384,  401,  471,  514,  576,
        605,  648,  658,  702,  793,  805,  815,  818,  833,  916,  969,
        987, 1063], dtype=int32)

In [34]:
np.cumsum(b, axis = 0)

array([[ 90,  52,   6,  29],
       [144, 150,  61,  46],
       [214, 193, 123,  75],
       [257, 203, 167, 166],
       [269, 213, 170, 181],
       [352, 266, 188, 257]], dtype=int32)

In [35]:
np.cumsum(b, axis = 1)

array([[ 90, 142, 148, 177],
       [ 54, 152, 207, 224],
       [ 70, 113, 175, 204],
       [ 43,  53,  97, 188],
       [ 12,  22,  25,  40],
       [ 83, 136, 154, 230]], dtype=int32)

In [32]:
# np.cumprod 
# works the same but not adds it product them

In [36]:
a

array([26, 23, 71, 51, 42, 82, 33, 94,  9, 79, 79, 12, 29, 94, 63])

In [37]:
np.cumprod(a)

array([         26,         598,       42458,     2165358,    90945036,
       -1132441640,  1284131544,   449280848,  -251439664,  1611103024,
       -1571879984, -1682690624, -1553387840,    10431104,   657159552],
      dtype=int32)

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html