### np.sort

Return a sorted copy of an array.
It returns a copy of the original array, so no changes will happen to the original array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np

a = np.random.randint(1, 100, 15)
a

array([65, 75, 13, 51,  2,  8, 44, 49, 89, 97, 23, 18, 88,  3, 24])

In [2]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[30, 93,  7, 14],
       [71, 39,  8, 68],
       [41, 56, 74, 51],
       [97, 83, 73, 76],
       [17, 69, 73, 33],
       [16,  7, 74,  6]])

In [3]:
np.sort(a)

array([ 2,  3,  8, 13, 18, 23, 24, 44, 49, 51, 65, 75, 88, 89, 97])

In [7]:
# decending wise sorting
np.sort(a)[::-1]

array([97, 89, 88, 75, 65, 51, 49, 44, 24, 23, 18, 13,  8,  3,  2])

In [5]:
a

array([65, 75, 13, 51,  2,  8, 44, 49, 89, 97, 23, 18, 88,  3, 24])

In [4]:
np.sort(b)

array([[ 7, 14, 30, 93],
       [ 8, 39, 68, 71],
       [41, 51, 56, 74],
       [73, 76, 83, 97],
       [17, 33, 69, 73],
       [ 6,  7, 16, 74]])

In [6]:
# axis = 0 -> column
# axis = 1 -> row
np.sort(b, axis = 0)

array([[16,  7,  7,  6],
       [17, 39,  8, 14],
       [30, 56, 73, 33],
       [41, 69, 73, 51],
       [71, 83, 74, 68],
       [97, 93, 74, 76]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
# code
# a
np.append(a, 200)

array([ 65,  75,  13,  51,   2,   8,  44,  49,  89,  97,  23,  18,  88,
         3,  24, 200])

In [12]:
# b
np.append(b, np.ones((b.shape[0], 1)), axis = 1)

array([[30., 93.,  7., 14.,  1.],
       [71., 39.,  8., 68.,  1.],
       [41., 56., 74., 51.,  1.],
       [97., 83., 73., 76.,  1.],
       [17., 69., 73., 33.,  1.],
       [16.,  7., 74.,  6.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [13]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
# axis = 0 -> column
# axis = 1 -> row
np.concatenate((c, d), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c, d), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [16]:
# code
e = np.array([1, 1, 2, 3, 2, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [17]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [18]:
a

array([65, 75, 13, 51,  2,  8, 44, 49, 89, 97, 23, 18, 88,  3, 24])

In [21]:
np.expand_dims(a, axis = 0).shape

(1, 15)

In [22]:
np.expand_dims(a, axis = 1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [23]:
a

array([65, 75, 13, 51,  2,  8, 44, 49, 89, 97, 23, 18, 88,  3, 24])

In [24]:
# find all indices with value greater than 50
np.where(a > 50)

(array([ 0,  1,  3,  8,  9, 12], dtype=int64),)

In [25]:
# replace all values > 50 with 0
# np.where(condition, true, false)
np.where(a > 50, 0, a)

array([ 0,  0, 13,  0,  2,  8, 44, 49,  0,  0, 23, 18,  0,  3, 24])

In [26]:
# replace all even numbers with 0
np.where(a%2 == 0, 0, a)

array([65, 75, 13, 51,  0,  0,  0, 49, 89, 97, 23,  0,  0,  3,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [27]:
a

array([65, 75, 13, 51,  2,  8, 44, 49, 89, 97, 23, 18, 88,  3, 24])

In [28]:
np.argmax(a)

9

In [29]:
b

array([[30, 93,  7, 14],
       [71, 39,  8, 68],
       [41, 56, 74, 51],
       [97, 83, 73, 76],
       [17, 69, 73, 33],
       [16,  7, 74,  6]])

In [31]:
# axis = 0 -> column
# axis = 1 -> row
np.argmax(b, axis = 0)

array([3, 0, 2, 3], dtype=int64)

In [32]:
np.argmax(b, axis = 1)

array([1, 0, 2, 0, 2, 2], dtype=int64)

Extra: np.argmin

In [36]:
a

array([65, 75, 13, 51,  2,  8, 44, 49, 89, 97, 23, 18, 88,  3, 24])

In [33]:
np.argmin(a)

4

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html